<?php
// Route table. Each route: [method, path, 'controller_file@function', [middleware...]].
// Middleware runs in order. 'auth' requires a session. 'csrf' verifies the
// token (declare on every write). 'rbac:<permission>' checks the permission.
// 'module:<key>' additionally requires the module to be visible to the user,
// so hiding a module also blocks direct URL access.
// {id} matches digits, {token} matches url-safe base64.

return [
    // First-run setup (reachable only until setup is completed)
    ['GET',    '/setup',                      'setup@index',                []],
    ['POST',   '/setup',                      'setup@submit',               ['csrf']],

    // Auth
    ['GET',    '/login',                      'auth@login_form',            []],
    ['POST',   '/login',                      'auth@login_submit',          ['throttle']],
    ['POST',   '/logout',                     'auth@logout',                ['auth', 'csrf']],
    ['GET',    '/account/password',           'auth@password_form',         ['auth']],
    ['POST',   '/account/password',           'auth@password_submit',       ['auth', 'csrf']],

    // Two-factor: challenge at login, and enrolment from the account area.
    ['GET',    '/login/verify',               'auth@totp_challenge_form',   []],
    ['POST',   '/login/verify',               'auth@totp_challenge_submit', ['throttle', 'csrf']],
    ['GET',    '/account/two-factor',          'auth@totp_setup_form',           ['auth']],
    ['POST',   '/account/two-factor/enable',   'auth@totp_enable',               ['auth', 'csrf']],
    ['POST',   '/account/two-factor/disable',  'auth@totp_disable',              ['auth', 'csrf']],
    ['POST',   '/account/two-factor/recovery', 'auth@totp_regenerate_recovery',  ['auth', 'csrf']],
    ['GET',    '/forgot-password',            'auth@forgot_form',           []],
    ['POST',   '/forgot-password',            'auth@forgot_submit',         ['throttle']],
    ['GET',    '/reset-password/{token}',     'auth@reset_form',            []],
    ['POST',   '/reset-password',             'auth@reset_submit',          ['throttle']],

    // Dashboard and shell services
    ['GET',    '/',                           'dashboard@home',             ['auth']],
    ['GET',    '/dashboard',                  'dashboard@index',            ['auth', 'rbac:dashboard.view', 'module:dashboard']],
    ['GET',    '/api/search',                 'search@palette',             ['auth']],
    ['GET',    '/notifications',              'notifications@list_json',    ['auth']],
    ['GET',    '/notifications/unseen-count', 'notifications@unseen_count',  ['auth']],
    ['POST',   '/notifications/seen',         'notifications@mark_seen',     ['auth', 'csrf']],
    ['POST',   '/notifications/read-all',     'notifications@mark_all_read', ['auth', 'csrf']],
    ['POST',   '/notifications/{id}/read',    'notifications@mark_one_read', ['auth', 'csrf']],

    // People
    ['GET',    '/people',                     'people@index',               ['auth', 'rbac:people.view', 'module:people']],
    ['GET',    '/people/org-chart',           'people@org_chart',           ['auth', 'rbac:people.view', 'module:people']],
    ['GET',    '/people/{id}',                'people@show',                ['auth', 'rbac:people.view', 'module:people']],
    ['GET',    '/api/people',                 'people@list_json',           ['auth', 'rbac:people.view']],
    ['GET',    '/api/people/{id}',            'people@detail_json',         ['auth', 'rbac:people.view']],
    ['POST',   '/people',                     'people@create',              ['auth', 'csrf', 'rbac:people.create']],
    ['PATCH',  '/people/{id}',                'people@update',              ['auth', 'csrf', 'rbac:people.edit']],
    ['POST',   '/people/{id}/terminate',      'people@terminate',           ['auth', 'csrf', 'rbac:people.terminate']],

    // Documents (vault on the person)
    ['POST',   '/people/{id}/documents',      'documents@upload',           ['auth', 'csrf', 'rbac:documents.upload']],
    ['GET',    '/api/people/{id}/documents',  'documents@list_json',        ['auth', 'rbac:documents.view']],
    ['POST',   '/documents/{id}/link',        'documents@issue_link',       ['auth', 'csrf', 'rbac:documents.view']],
    ['DELETE', '/documents/{id}',             'documents@destroy',          ['auth', 'csrf', 'rbac:documents.view_all']],
    ['GET',    '/files/{token}',              'documents@download',         ['auth']],

    // Attendance
    ['GET',    '/attendance',                 'attendance@index',           ['auth', 'rbac:attendance.view', 'module:attendance']],
    ['POST',   '/attendance/check-in',        'attendance@check_in',        ['auth', 'csrf', 'rbac:attendance.record']],
    ['POST',   '/attendance/check-out',       'attendance@check_out',       ['auth', 'csrf', 'rbac:attendance.record']],
    ['GET',    '/api/attendance/me',          'attendance@me_json',         ['auth', 'rbac:attendance.view']],
    ['GET',    '/api/attendance/team',        'attendance@team_json',       ['auth', 'rbac:attendance.view_all']],
    ['PATCH',  '/attendance/{id}',            'attendance@correct',         ['auth', 'csrf', 'rbac:attendance.correct']],

    // Leave
    ['GET',    '/leave',                      'leave@index',                ['auth', 'rbac:leave.view', 'module:leave']],
    ['POST',   '/leave',                      'leave@request_leave',        ['auth', 'csrf', 'rbac:leave.request']],
    ['POST',   '/leave/{id}/approve',         'leave@approve',              ['auth', 'csrf', 'rbac:leave.approve']],
    ['POST',   '/leave/{id}/reject',          'leave@reject',               ['auth', 'csrf', 'rbac:leave.approve']],
    ['POST',   '/leave/{id}/cancel',          'leave@cancel',               ['auth', 'csrf', 'rbac:leave.request']],
    ['GET',    '/api/leave/balance',          'leave@balance_json',         ['auth', 'rbac:leave.view']],
    ['GET',    '/api/leave/calendar',         'leave@calendar_json',        ['auth', 'rbac:leave.view']],
    ['GET',    '/api/leave/list',             'leave@list_json',            ['auth', 'rbac:leave.view']],

    // Projects and tasks
    ['GET',    '/projects',                   'projects@index',             ['auth', 'rbac:projects.view', 'module:projects']],
    ['GET',    '/projects/{id}',              'projects@show',              ['auth', 'rbac:projects.view', 'module:projects']],
    ['POST',   '/projects',                   'projects@create',            ['auth', 'csrf', 'rbac:projects.manage']],
    ['PATCH',  '/projects/{id}',              'projects@update',            ['auth', 'csrf', 'rbac:projects.manage']],
    ['GET',    '/api/tasks',                  'tasks@list_json',            ['auth', 'rbac:projects.view']],
    ['GET',    '/api/tasks/{id}',             'tasks@detail_json',          ['auth', 'rbac:projects.view']],
    ['POST',   '/tasks',                      'tasks@create',               ['auth', 'csrf', 'rbac:tasks.create']],
    ['PATCH',  '/tasks/{id}',                 'tasks@update',               ['auth', 'csrf', 'rbac:tasks.create']],
    ['PATCH',  '/tasks/{id}/status',          'tasks@set_status',           ['auth', 'csrf', 'rbac:tasks.create']],
    ['POST',   '/tasks/{id}/comments',        'tasks@add_comment',          ['auth', 'csrf', 'rbac:tasks.comment']],

    // Assets
    ['GET',    '/assets',                     'assets@index',               ['auth', 'rbac:assets.view', 'module:assets']],
    ['GET',    '/api/assets',                 'assets@list_json',           ['auth', 'rbac:assets.view']],
    ['GET',    '/api/assets/{id}',            'assets@detail_json',         ['auth', 'rbac:assets.view']],
    ['POST',   '/assets',                     'assets@create',              ['auth', 'csrf', 'rbac:assets.manage']],
    ['PATCH',  '/assets/{id}',                'assets@update',              ['auth', 'csrf', 'rbac:assets.manage']],
    ['POST',   '/assets/{id}/assign',         'assets@assign',              ['auth', 'csrf', 'rbac:assets.assign']],
    ['POST',   '/assets/{id}/return',         'assets@return_asset',        ['auth', 'csrf', 'rbac:assets.assign']],
    ['POST',   '/assets/import',              'assets@import_csv',          ['auth', 'csrf', 'rbac:assets.manage']],

    // Certifications
    ['GET',    '/certifications',             'certifications@index',       ['auth', 'rbac:certifications.view', 'module:certifications']],
    ['GET',    '/certifications/matrix',      'certifications@matrix',      ['auth', 'rbac:certifications.view', 'module:certifications']],
    ['GET',    '/api/certifications',         'certifications@list_json',   ['auth', 'rbac:certifications.view']],
    ['POST',   '/certifications',             'certifications@create',      ['auth', 'csrf', 'rbac:certifications.manage_own']],
    ['PATCH',  '/certifications/{id}',        'certifications@update',      ['auth', 'csrf', 'rbac:certifications.manage_own']],
    ['DELETE', '/certifications/{id}',        'certifications@destroy',     ['auth', 'csrf', 'rbac:certifications.manage_own']],
    ['POST',   '/certifications/{id}/file',   'certifications@attach_file',  ['auth', 'csrf', 'rbac:certifications.manage_own']],
    ['POST',   '/certifications/{id}/file-link', 'certifications@file_link', ['auth', 'csrf', 'rbac:certifications.view']],
    ['GET',    '/certifications/file/{token}','certifications@download_file',['auth', 'rbac:certifications.view']],

    // Company profile and compliance library
    ['GET',    '/company/documents',              'company@library',              ['auth', 'rbac:company_docs.view', 'module:company_docs']],
    ['GET',    '/api/company/documents',          'company@documents_json',       ['auth', 'rbac:company_docs.view']],
    ['POST',   '/company/documents',              'company@upload_document',      ['auth', 'csrf', 'rbac:company_docs.manage']],
    ['PATCH',  '/company/documents/{id}',         'company@update_document',      ['auth', 'csrf', 'rbac:company_docs.manage']],
    ['DELETE', '/company/documents/{id}',         'company@delete_document',      ['auth', 'csrf', 'rbac:company_docs.manage']],
    ['POST',   '/company/documents/{id}/link',    'company@document_link',        ['auth', 'csrf', 'rbac:company_docs.view']],
    ['GET',    '/company/files/{token}',          'company@download_document',    ['auth', 'rbac:company_docs.view']],
    ['GET',    '/api/company/references',         'company@references_json',      ['auth', 'rbac:company_docs.view']],
    ['POST',   '/company/references',             'company@create_reference',     ['auth', 'csrf', 'rbac:company_docs.manage']],
    ['PATCH',  '/company/references/{id}',        'company@update_reference',     ['auth', 'csrf', 'rbac:company_docs.manage']],
    ['DELETE', '/company/references/{id}',        'company@delete_reference',     ['auth', 'csrf', 'rbac:company_docs.manage']],
    ['POST',   '/company/references/{id}/cert-link', 'company@reference_cert_link', ['auth', 'csrf', 'rbac:company_docs.view']],
    ['GET',    '/company/references/file/{token}','company@download_reference_cert', ['auth', 'rbac:company_docs.view']],

    // Company profile editor, in the admin Settings area
    ['GET',    '/admin/company-profile',          'company@profile_form',         ['auth', 'rbac:admin.settings', 'module:admin_settings']],
    ['POST',   '/admin/company-profile',          'company@profile_save',         ['auth', 'csrf', 'rbac:admin.settings']],

    // Clients and opportunities
    ['GET',    '/clients',                        'clients@index',                ['auth', 'rbac:clients.view', 'module:clients']],
    ['GET',    '/clients/{id}',                   'clients@show',                 ['auth', 'rbac:clients.view', 'module:clients']],
    ['GET',    '/api/clients',                    'clients@list_json',            ['auth', 'rbac:clients.view']],
    ['POST',   '/clients',                        'clients@create',               ['auth', 'csrf', 'rbac:clients.manage']],
    ['PATCH',  '/clients/{id}',                   'clients@update',               ['auth', 'csrf', 'rbac:clients.manage']],
    ['DELETE', '/clients/{id}',                   'clients@destroy',              ['auth', 'csrf', 'rbac:clients.manage']],
    ['POST',   '/clients/{id}/contacts',          'clients@add_contact',          ['auth', 'csrf', 'rbac:clients.manage']],
    ['DELETE', '/clients/contacts/{id}',          'clients@delete_contact',       ['auth', 'csrf', 'rbac:clients.manage']],
    ['GET',    '/api/opportunities',              'clients@opportunities_json',   ['auth', 'rbac:clients.view']],
    ['POST',   '/opportunities',                  'clients@create_opportunity',   ['auth', 'csrf', 'rbac:clients.manage']],
    ['PATCH',  '/opportunities/{id}',             'clients@update_opportunity',   ['auth', 'csrf', 'rbac:clients.manage']],
    ['DELETE', '/opportunities/{id}',             'clients@delete_opportunity',   ['auth', 'csrf', 'rbac:clients.manage']],

    // Tenders: record, pipeline, and every bid sub-record
    ['GET',    '/tenders',                        'tenders@index',                ['auth', 'rbac:tenders.view', 'module:tenders']],
    ['GET',    '/tenders/analytics',              'tenders@analytics',            ['auth', 'rbac:tenders.view', 'module:tenders']],
    ['GET',    '/tenders/{id}',                   'tenders@show',                 ['auth', 'rbac:tenders.view', 'module:tenders']],
    ['GET',    '/tenders/{id}/pack',              'tenders@export_pack',          ['auth', 'rbac:tenders.view', 'module:tenders']],
    ['GET',    '/api/tenders',                    'tenders@list_json',            ['auth', 'rbac:tenders.view']],
    ['POST',   '/tenders',                        'tenders@create',               ['auth', 'csrf', 'rbac:tenders.manage']],
    ['PATCH',  '/tenders/{id}',                   'tenders@update',               ['auth', 'csrf', 'rbac:tenders.manage']],
    ['DELETE', '/tenders/{id}',                   'tenders@destroy',              ['auth', 'csrf', 'rbac:tenders.manage']],
    ['POST',   '/tenders/{id}/go-assessment',     'tenders@save_go_assessment',   ['auth', 'csrf', 'rbac:tenders.manage']],
    ['POST',   '/tenders/{id}/requirements',      'tenders@add_requirement',      ['auth', 'csrf', 'rbac:tenders.manage']],
    ['PATCH',  '/tenders/requirements/{id}',      'tenders@update_requirement',   ['auth', 'csrf', 'rbac:tenders.manage']],
    ['DELETE', '/tenders/requirements/{id}',      'tenders@delete_requirement',   ['auth', 'csrf', 'rbac:tenders.manage']],
    ['POST',   '/tenders/{id}/documents',         'tenders@add_document',         ['auth', 'csrf', 'rbac:tenders.manage']],
    ['PATCH',  '/tenders/documents/{id}',         'tenders@update_document',      ['auth', 'csrf', 'rbac:tenders.manage']],
    ['DELETE', '/tenders/documents/{id}',         'tenders@delete_document',      ['auth', 'csrf', 'rbac:tenders.manage']],
    ['POST',   '/tenders/{id}/team',              'tenders@add_team',             ['auth', 'csrf', 'rbac:tenders.manage']],
    ['DELETE', '/tenders/team/{id}',              'tenders@delete_team',          ['auth', 'csrf', 'rbac:tenders.manage']],
    ['POST',   '/tenders/{id}/criteria',          'tenders@add_criterion',        ['auth', 'csrf', 'rbac:tenders.manage']],
    ['PATCH',  '/tenders/criteria/{id}',          'tenders@update_criterion',     ['auth', 'csrf', 'rbac:tenders.manage']],
    ['DELETE', '/tenders/criteria/{id}',          'tenders@delete_criterion',     ['auth', 'csrf', 'rbac:tenders.manage']],
    ['POST',   '/tenders/{id}/boq',               'tenders@add_boq',              ['auth', 'csrf', 'rbac:tenders.manage']],
    ['PATCH',  '/tenders/boq/{id}',               'tenders@update_boq',           ['auth', 'csrf', 'rbac:tenders.manage']],
    ['DELETE', '/tenders/boq/{id}',               'tenders@delete_boq',           ['auth', 'csrf', 'rbac:tenders.manage']],
    ['POST',   '/tenders/{id}/securities',        'tenders@add_security',         ['auth', 'csrf', 'rbac:tenders.manage']],
    ['PATCH',  '/tenders/securities/{id}',        'tenders@update_security',      ['auth', 'csrf', 'rbac:tenders.manage']],
    ['DELETE', '/tenders/securities/{id}',        'tenders@delete_security',      ['auth', 'csrf', 'rbac:tenders.manage']],
    ['POST',   '/tenders/{id}/outcome',           'tenders@set_outcome',          ['auth', 'csrf', 'rbac:tenders.manage']],

    // Suppliers and manufacturer authorizations
    ['GET',    '/suppliers',                      'suppliers@index',              ['auth', 'rbac:suppliers.view', 'module:suppliers']],
    ['GET',    '/suppliers/{id}',                 'suppliers@show',               ['auth', 'rbac:suppliers.view', 'module:suppliers']],
    ['GET',    '/api/suppliers',                  'suppliers@list_json',          ['auth', 'rbac:suppliers.view']],
    ['POST',   '/suppliers',                      'suppliers@create',             ['auth', 'csrf', 'rbac:suppliers.manage']],
    ['PATCH',  '/suppliers/{id}',                 'suppliers@update',             ['auth', 'csrf', 'rbac:suppliers.manage']],
    ['DELETE', '/suppliers/{id}',                 'suppliers@destroy',            ['auth', 'csrf', 'rbac:suppliers.manage']],
    ['POST',   '/suppliers/{id}/authorizations',  'suppliers@add_authorization',  ['auth', 'csrf', 'rbac:suppliers.manage']],
    ['PATCH',  '/suppliers/authorizations/{id}',  'suppliers@update_authorization', ['auth', 'csrf', 'rbac:suppliers.manage']],
    ['DELETE', '/suppliers/authorizations/{id}',  'suppliers@delete_authorization', ['auth', 'csrf', 'rbac:suppliers.manage']],
    ['POST',   '/suppliers/authorizations/{id}/link', 'suppliers@authorization_link', ['auth', 'csrf', 'rbac:suppliers.view']],
    ['GET',    '/suppliers/authorizations/file/{token}', 'suppliers@download_authorization', ['auth', 'rbac:suppliers.view']],

    // Procurement and office administration
    ['GET',    '/procurement',                    'procurement@index',            ['auth', 'rbac:procurement.view', 'module:procurement']],
    ['GET',    '/procurement/requisitions/{id}',  'procurement@requisition',      ['auth', 'rbac:procurement.view', 'module:procurement']],
    ['GET',    '/procurement/orders/{id}',        'procurement@order',            ['auth', 'rbac:procurement.view', 'module:procurement']],
    ['POST',   '/procurement/requests',           'procurement@create_request',   ['auth', 'csrf', 'rbac:procurement.request']],
    ['PATCH',  '/procurement/requests/{id}',      'procurement@update_request',   ['auth', 'csrf', 'rbac:procurement.request']],
    ['DELETE', '/procurement/requests/{id}',      'procurement@delete_request',   ['auth', 'csrf', 'rbac:procurement.request']],
    ['POST',   '/procurement/requisitions',       'procurement@create_requisition', ['auth', 'csrf', 'rbac:procurement.manage']],
    ['POST',   '/procurement/requisitions/{id}/submit',  'procurement@submit_requisition', ['auth', 'csrf', 'rbac:procurement.manage']],
    ['POST',   '/procurement/requisitions/{id}/decide',  'procurement@decide_requisition', ['auth', 'csrf', 'rbac:procurement.approve']],
    ['POST',   '/procurement/requisitions/{id}/fund-release', 'procurement@add_fund_release', ['auth', 'csrf', 'rbac:procurement.approve']],
    ['POST',   '/procurement/orders',             'procurement@create_order',     ['auth', 'csrf', 'rbac:procurement.manage']],
    ['PATCH',  '/procurement/orders/{id}',        'procurement@update_order',     ['auth', 'csrf', 'rbac:procurement.manage']],
    ['POST',   '/procurement/orders/{id}/items',  'procurement@add_order_item',   ['auth', 'csrf', 'rbac:procurement.manage']],
    ['DELETE', '/procurement/order-items/{id}',   'procurement@delete_order_item', ['auth', 'csrf', 'rbac:procurement.manage']],
    ['POST',   '/procurement/orders/{id}/receipts', 'procurement@add_receipt',    ['auth', 'csrf', 'rbac:procurement.manage']],
    ['GET',    '/budgets',                        'procurement@budgets',          ['auth', 'rbac:budgets.view', 'module:budgets']],
    ['POST',   '/budgets',                        'procurement@save_budget',      ['auth', 'csrf', 'rbac:budgets.manage']],
    ['DELETE', '/budgets/{id}',                   'procurement@delete_budget',    ['auth', 'csrf', 'rbac:budgets.manage']],

    // Payroll and HR: personal records, pay components, salary structures
    ['GET',    '/payroll',                        'payroll@index',                ['auth', 'rbac:payroll.view_own', 'module:payroll']],
    ['GET',    '/payroll/components',             'payroll@components',            ['auth', 'rbac:payroll.manage', 'module:payroll']],
    ['GET',    '/payroll/records/{id}',           'payroll@records',              ['auth', 'rbac:payroll.view_own', 'module:payroll']],
    ['GET',    '/api/payroll/structure/{id}',     'payroll@structure_json',       ['auth', 'rbac:payroll.view_own']],
    ['POST',   '/payroll/records/{id}/details',   'payroll@save_details',         ['auth', 'csrf', 'rbac:payroll.view_own']],
    ['POST',   '/payroll/records/{id}/beneficiaries', 'payroll@add_beneficiary',  ['auth', 'csrf', 'rbac:payroll.view_own']],
    ['DELETE', '/payroll/beneficiaries/{id}',     'payroll@delete_beneficiary',   ['auth', 'csrf', 'rbac:payroll.view_own']],
    ['POST',   '/payroll/records/{id}/bank',      'payroll@add_bank',             ['auth', 'csrf', 'rbac:payroll.view_own']],
    ['DELETE', '/payroll/bank/{id}',              'payroll@delete_bank',          ['auth', 'csrf', 'rbac:payroll.view_own']],
    ['POST',   '/payroll/records/{id}/structure', 'payroll@save_structure',       ['auth', 'csrf', 'rbac:payroll.manage']],
    ['POST',   '/payroll/components',             'payroll@add_component',        ['auth', 'csrf', 'rbac:payroll.manage']],
    ['PATCH',  '/payroll/components/{id}',        'payroll@update_component',     ['auth', 'csrf', 'rbac:payroll.manage']],
    ['DELETE', '/payroll/components/{id}',        'payroll@delete_component',     ['auth', 'csrf', 'rbac:payroll.manage']],
    ['GET',    '/payroll/runs',                   'payroll@runs',                 ['auth', 'rbac:payroll.view_all', 'module:payroll']],
    ['GET',    '/payroll/runs/{id}',              'payroll@run',                  ['auth', 'rbac:payroll.view_all', 'module:payroll']],
    ['POST',   '/payroll/runs',                   'payroll@create_run',           ['auth', 'csrf', 'rbac:payroll.manage']],
    ['POST',   '/payroll/runs/{id}/compute',      'payroll@compute_run',          ['auth', 'csrf', 'rbac:payroll.manage']],
    ['POST',   '/payroll/runs/{id}/approve',      'payroll@approve_run',          ['auth', 'csrf', 'rbac:payroll.approve']],
    ['POST',   '/payroll/runs/{id}/pay',          'payroll@pay_run',              ['auth', 'csrf', 'rbac:payroll.approve']],
    ['DELETE', '/payroll/runs/{id}',              'payroll@delete_run',           ['auth', 'csrf', 'rbac:payroll.manage']],
    ['GET',    '/payroll/payslips/{id}',          'payroll@payslip',              ['auth', 'rbac:payroll.view_own', 'module:payroll']],
    ['POST',   '/payroll/payslips/{id}/email',    'payroll@email_payslip',        ['auth', 'csrf', 'rbac:payroll.view_all']],
    ['GET',    '/payroll/loans',                  'payroll@loans',                ['auth', 'rbac:payroll.manage', 'module:payroll']],
    ['POST',   '/payroll/loans',                  'payroll@create_loan',          ['auth', 'csrf', 'rbac:payroll.manage']],
    ['POST',   '/payroll/loans/{id}/decide',      'payroll@decide_loan',          ['auth', 'csrf', 'rbac:payroll.approve']],

    // Expenses and petty cash
    ['GET',    '/expenses',                       'expenses@index',               ['auth', 'rbac:expenses.submit', 'module:expenses']],
    ['GET',    '/expenses/petty-cash',            'expenses@petty_cash',          ['auth', 'rbac:pettycash.manage', 'module:expenses']],
    ['GET',    '/expenses/receipts/file/{token}', 'expenses@download_receipt',    ['auth', 'rbac:expenses.submit']],
    ['GET',    '/expenses/{id}',                  'expenses@claim',               ['auth', 'rbac:expenses.submit', 'module:expenses']],
    ['POST',   '/expenses',                       'expenses@create_claim',        ['auth', 'csrf', 'rbac:expenses.submit']],
    ['PATCH',  '/expenses/{id}',                  'expenses@update_claim',        ['auth', 'csrf', 'rbac:expenses.submit']],
    ['DELETE', '/expenses/{id}',                  'expenses@delete_claim',        ['auth', 'csrf', 'rbac:expenses.submit']],
    ['POST',   '/expenses/{id}/submit',           'expenses@submit_claim',        ['auth', 'csrf', 'rbac:expenses.submit']],
    ['POST',   '/expenses/{id}/decide',           'expenses@decide_claim',        ['auth', 'csrf', 'rbac:expenses.approve']],
    ['POST',   '/expenses/{id}/reimburse',        'expenses@reimburse_claim',     ['auth', 'csrf', 'rbac:expenses.approve']],
    ['POST',   '/expenses/{id}/lines',            'expenses@add_line',            ['auth', 'csrf', 'rbac:expenses.submit']],
    ['PATCH',  '/expenses/lines/{id}',            'expenses@update_line',         ['auth', 'csrf', 'rbac:expenses.submit']],
    ['DELETE', '/expenses/lines/{id}',            'expenses@delete_line',         ['auth', 'csrf', 'rbac:expenses.submit']],
    ['POST',   '/expenses/lines/{id}/receipt-link', 'expenses@receipt_link',      ['auth', 'csrf', 'rbac:expenses.submit']],
    ['POST',   '/expenses/petty-cash',            'expenses@add_petty_entry',     ['auth', 'csrf', 'rbac:pettycash.manage']],
    ['DELETE', '/expenses/petty-cash/{id}',       'expenses@delete_petty_entry',  ['auth', 'csrf', 'rbac:pettycash.manage']],

    // Timesheets and billable hours
    ['GET',    '/timesheets',                     'timesheets@index',             ['auth', 'rbac:timesheets.log', 'module:timesheets']],
    ['GET',    '/api/timesheets',                 'timesheets@list_json',         ['auth', 'rbac:timesheets.log']],
    ['GET',    '/api/timesheets/project/{id}/tasks', 'timesheets@project_tasks_json', ['auth', 'rbac:timesheets.log']],
    ['POST',   '/timesheets',                     'timesheets@create_entry',      ['auth', 'csrf', 'rbac:timesheets.log']],
    ['PATCH',  '/timesheets/{id}',                'timesheets@update_entry',      ['auth', 'csrf', 'rbac:timesheets.log']],
    ['DELETE', '/timesheets/{id}',                'timesheets@delete_entry',      ['auth', 'csrf', 'rbac:timesheets.log']],

    // Internal helpdesk
    ['GET',    '/helpdesk',                       'helpdesk@index',               ['auth', 'rbac:helpdesk.raise', 'module:helpdesk']],
    ['GET',    '/helpdesk/{id}',                  'helpdesk@show',                ['auth', 'rbac:helpdesk.raise', 'module:helpdesk']],
    ['POST',   '/helpdesk',                       'helpdesk@create',              ['auth', 'csrf', 'rbac:helpdesk.raise']],
    ['PATCH',  '/helpdesk/{id}',                  'helpdesk@update',              ['auth', 'csrf', 'rbac:helpdesk.manage']],
    ['POST',   '/helpdesk/{id}/comments',         'helpdesk@add_comment',         ['auth', 'csrf', 'rbac:helpdesk.raise']],

    // Noticeboard and policies
    ['GET',    '/noticeboard',                    'noticeboard@index',            ['auth', 'rbac:noticeboard.view', 'module:noticeboard']],
    ['POST',   '/noticeboard/announcements',      'noticeboard@create_announcement', ['auth', 'csrf', 'rbac:noticeboard.manage']],
    ['PATCH',  '/noticeboard/announcements/{id}', 'noticeboard@update_announcement', ['auth', 'csrf', 'rbac:noticeboard.manage']],
    ['DELETE', '/noticeboard/announcements/{id}', 'noticeboard@delete_announcement', ['auth', 'csrf', 'rbac:noticeboard.manage']],
    ['POST',   '/noticeboard/policies',           'noticeboard@upload_policy',     ['auth', 'csrf', 'rbac:noticeboard.manage']],
    ['DELETE', '/noticeboard/policies/{id}',      'noticeboard@delete_policy',     ['auth', 'csrf', 'rbac:noticeboard.manage']],
    ['POST',   '/noticeboard/policies/{id}/link', 'noticeboard@policy_link',       ['auth', 'csrf', 'rbac:noticeboard.view']],
    ['GET',    '/noticeboard/policies/file/{token}', 'noticeboard@download_policy', ['auth', 'rbac:noticeboard.view']],

    // Fleet and vehicles
    ['GET',    '/fleet',                          'fleet@index',                  ['auth', 'rbac:fleet.view', 'module:fleet']],
    ['GET',    '/api/fleet',                      'fleet@list_json',              ['auth', 'rbac:fleet.view']],
    ['GET',    '/api/fleet/{id}',                 'fleet@detail_json',            ['auth', 'rbac:fleet.view']],
    ['POST',   '/fleet',                          'fleet@create',                 ['auth', 'csrf', 'rbac:fleet.manage']],
    ['PATCH',  '/fleet/{id}',                     'fleet@update',                 ['auth', 'csrf', 'rbac:fleet.manage']],
    ['DELETE', '/fleet/{id}',                     'fleet@destroy',                ['auth', 'csrf', 'rbac:fleet.manage']],
    ['POST',   '/fleet/{id}/logs',                'fleet@add_log',                ['auth', 'csrf', 'rbac:fleet.manage']],

    // Contracts and renewals
    ['GET',    '/contracts',                      'contracts@index',              ['auth', 'rbac:contracts.view', 'module:contracts']],
    ['GET',    '/api/contracts',                  'contracts@list_json',          ['auth', 'rbac:contracts.view']],
    ['POST',   '/contracts',                      'contracts@create',             ['auth', 'csrf', 'rbac:contracts.manage']],
    ['PATCH',  '/contracts/{id}',                 'contracts@update',             ['auth', 'csrf', 'rbac:contracts.manage']],
    ['DELETE', '/contracts/{id}',                 'contracts@destroy',            ['auth', 'csrf', 'rbac:contracts.manage']],
    ['POST',   '/contracts/{id}/file-link',       'contracts@file_link',          ['auth', 'csrf', 'rbac:contracts.view']],
    ['GET',    '/contracts/file/{token}',         'contracts@download',           ['auth', 'rbac:contracts.view']],

    // Admin
    ['GET',    '/admin/users',                'admin_users@index',          ['auth', 'rbac:admin.users', 'module:admin_users']],
    ['POST',   '/admin/users',                'admin_users@create',         ['auth', 'csrf', 'rbac:admin.users']],
    ['PATCH',  '/admin/users/{id}',           'admin_users@update',         ['auth', 'csrf', 'rbac:admin.users']],
    ['POST',   '/admin/users/{id}/reset-password', 'admin_users@reset_password', ['auth', 'csrf', 'rbac:admin.users']],
    ['GET',    '/admin/roles',                'admin_roles@index',          ['auth', 'rbac:admin.roles', 'module:admin_roles']],
    ['POST',   '/admin/roles/permissions',    'admin_roles@save_permissions', ['auth', 'csrf', 'rbac:admin.roles']],
    ['POST',   '/admin/roles/visibility',     'admin_roles@save_visibility',  ['auth', 'csrf', 'rbac:admin.roles']],
    ['POST',   '/admin/users/{id}/overrides', 'admin_roles@save_user_overrides', ['auth', 'csrf', 'rbac:admin.roles']],
    ['GET',    '/api/admin/users/{id}/access','admin_roles@user_access_json', ['auth', 'rbac:admin.roles']],
    ['GET',    '/admin/audit',                'admin_audit@index',          ['auth', 'rbac:admin.audit', 'module:admin_audit']],
    ['GET',    '/api/admin/audit',            'admin_audit@list_json',      ['auth', 'rbac:admin.audit']],
    ['GET',    '/admin/settings',             'admin_settings@index',       ['auth', 'rbac:admin.settings', 'module:admin_settings']],
    ['POST',   '/admin/settings',             'admin_settings@save',        ['auth', 'csrf', 'rbac:admin.settings']],
    ['POST',   '/admin/settings/leave-types', 'admin_settings@save_leave_type', ['auth', 'csrf', 'rbac:admin.settings']],
    ['GET',    '/admin/modules',              'admin_settings@modules',         ['auth', 'rbac:admin.settings', 'module:admin_settings']],
    ['POST',   '/admin/modules',              'admin_settings@save_modules',    ['auth', 'csrf', 'rbac:admin.settings']],
    ['GET',    '/admin/about',                'admin_settings@about',           ['auth', 'rbac:admin.settings', 'module:admin_settings']],
    ['POST',   '/admin/about/license',        'admin_settings@save_license',    ['auth', 'csrf', 'rbac:admin.settings']],
    ['GET',    '/api/admin/system-check',     'admin_settings@system_check',    ['auth', 'rbac:admin.settings']],
    ['POST',   '/api/admin/test-asset',       'admin_settings@test_asset_save', ['auth', 'csrf', 'rbac:admin.settings']],
];
